version: 2.1
orbs:
  golangci-lint: ory/golangci@0.0.4
  go: circleci/go@1.4.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - setup_remote_docker:
        version: 19.03.13
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  build:
    jobs:
      - golangci-lint/lint
      - build
