version: 2.1
orbs:
  golangci-lint: ory/golangci@0.0.4
  go: circleci/go@1.1.1
jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
workflows:
  build:
    jobs:
      - golangci-lint/lint
      - build
      - go test ./...
